# Format: key|url|name
Rocking_It|https://music.apple.com/us/playlist/rocking-it/pl.u-oZyl3VetPdVGYp|Rocking It
Thumbs_Up|https://music.apple.com/us/playlist/hollys-thumbs-up/pl.u-KVXBD4JFzX7L5V|Thumbs Up
Pop_Workout|https://music.apple.com/us/playlist/pop-workout/pl.daa788c0ab3841febf12046d5bd67546|Pop Workout
Red_Bull_Offroad_Mix|https://music.apple.com/us/playlist/red-bull-offroad-mix/pl.808d620b737b47b987725e01a9feab29|Red Bull Offroad Mix
