# Format: key|url|name
Rocking_It|https://music.apple.com/us/playlist/rocking-it/pl.u-oZyl3VetPdVGYp|Rocking It
Thumbs_Up|https://music.apple.com/us/playlist/hollys-thumbs-up/pl.u-KVXBD4JFzX7L5V|Thumbs Up
Pop_Workout|https://music.apple.com/us/playlist/pop-workout/pl.daa788c0ab3841febf12046d5bd67546|Pop Workout
Red_Bull_Offroad_Mix|https://music.apple.com/us/playlist/red-bull-offroad-mix/pl.808d620b737b47b987725e01a9feab29|Red Bull Offroad Mix
Singing_In_The_Car|https://music.apple.com/us/playlist/singing-in-the-car/pl.f06212669e024908b3c5eb10acc13f68|Singing In The Car
Tailgating|https://music.apple.com/us/playlist/tailgating/pl.5fa6dda82c3347208d0897a31c50204d|Tailgating
Girls_Night_Out|https://music.apple.com/us/playlist/girls-night-out/pl.2e1baad7a93a46d4befbbf94201f9112|Girls Night Out
